#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright (C) Apr 13, 2014 Han Zhao <han.zhao@uwaterloo.ca>
'''
@purpose: Utility functions provided for loading and saving data
          generated by HMM.
@author: keira
'''
import csv
import numpy as np

def load_sequences(filename):
    '''
    @filename: string. Path to the file which contains observation 
                sequences. Note that since each observation sequence
                can have variable length, the return value of this 
                function is [np.array]
    '''
    sequences = []
    with file(filename, "rb") as fin:
        reader = csv.reader(fin)
        for line in reader:
            sequences.append(np.asarray(map(int, line)))
    return sequences

def save_sequences(filename, sequences):
    '''
    @filename: string. Path to the file which is used to store sequences
                of observations
    '''
    with file(filename, "wb") as fout:
        writer = csv.writer(fout, delimiter=",")
        writer.writerows(sequences)
        
        